.\" Process this file with
.\" groff -man -Tutf8 roccatpyracontrol.1
.\"
.TH ROCCATPYRACONTROL 1 "AUGUST 2010" "Stefan Achatz" "Benutzerhandbücher"
.SH NAME
roccatpyracontrol \- Ein Hilfsprogramm um die erweiterten Funktionen der Pyra zu nutzen.
.SH SYNTAX
.B roccatpyracontrol
[
.B -fhv
] [
.B -a
.i NUMMER
] [
.B -l
.I NUMMER
] [
.B -r
.I DATEINAME
] [
.B -s
.I NUMMER
] [
.B -w
.I DATEINAME
] [
.BI --activate-profile= NUMMER
] [
.B --actual-profile
] [
.B --help
] [
.BI --load= NUMMER
] [
.B --read-firmware
] [
.BI --read-rmp= DATEINAME
] [
.BI --reset
] [
.BI --save= NUMMER
] [
.B --version
] [
.BI --write-rmp= DATEINAME
]
.SH BESCHREIBUNG
Diese Konsolenanwendung ermöglicht es die erweiterten Funktionen der Pyra zu nutzen.
.SH OPTIONEN
.IP "-h, --help"
Zeige die Hilfeliste.
.IP "-a, --activate-profile=NUMMER"
Aktiviert das angegebene Profil. Das aktive Profil ist permanent, d.h. ist zugleich
das Startup-Profil der Pyra.
.IP "--actual-profile"
Gibt die Nummer des aktiven Profils aus.
.IP "-f, --read-firmware"
Gibt die Firmwareversion der Pyra aus.
.IP "-l, --load=NUMMER"
Lädt das Profil aus der Maus, sowie das dazugehörige hinterlegte Profil.
Sollten diese sich unterscheiden wird eine Warnung ausgegeben und das hinterlegte
Profil weiterverwendet.
.IP "-r, --read-rmp=DATEINAME"
Lies eine rmp-Datei in den Speicher. 
.IP "--reset"
Setzt das Gerät auf Standardeinstellungen zurück.
.IP "-s, --save=NUMMER"
Speichert das Profil aus dem Speicher in der Maus und im hinterlegten Profil.
.IP "-v, --version"
Zeige die Programmversion.
.IP "-w, --write-rmp=DATEINAME"
Schreibe das im Speicher enthaltene Profil als rmp-Datei.
.SH AUTOR
Stefan Achatz <erazor_de@users.sourceforge.net>
